#include "io/bookshelf_writer.h"

#include <cstdio>
#include <stdexcept>
#include <vector>

#include "db/place_db.h"

namespace sp {
namespace {

const char* kOrientNames[] = {"N", "E", "S", "W", "FN", "FE", "FS", "FW"};

}  // namespace

void BookshelfWriter::writePl(const std::string& path, const PlaceDB& db) {
    std::FILE* f = std::fopen(path.c_str(), "wb");
    if (!f) throw std::runtime_error("cannot write: " + path);

    std::fputs("UCLA pl 1.0\n", f);
    std::fputs("# Generated by superPlace\n\n", f);

    // 输出顺序按节点索引，保证同输入下逐字节可复现（铁律 7）
    for (int i = 0; i < db.numNodes; ++i) {
        // 铁律 2：中心 -> 左下角，全项目唯一的反向换算点
        const double llx = static_cast<double>(db.node_x[i]) - 0.5 * db.node_w[i];
        const double lly = static_cast<double>(db.node_y[i]) - 0.5 * db.node_h[i];
        const uint8_t o = db.node_orient[i] < 8 ? db.node_orient[i] : 0;

        std::fprintf(f, "%s\t%.6f\t%.6f\t: %s", db.node_name[i].c_str(), llx, lly,
                     kOrientNames[o]);
        if (db.isFixed(i)) std::fputs(" /FIXED", f);
        std::fputc('\n', f);
    }

    std::fclose(f);
}

}  // namespace sp
